#ifndef CONFIG_H
#define CONFIG_H

// window.h
#define WINDOW_WIDTH 800
#define WINDOW_HEIGHT 600
#define WINDOW_TITLE "OpenGL"
#define WINDOW_X_POS SDL_WINDOWPOS_CENTERED
#define WINDOW_Y_POS SDL_WINDOWPOS_CENTERED
#define WINDOW_FLAGS SDL_WINDOW_OPENGL | SDL_WINDOW_SHOWN
#define WINDOW_GL_CONTEXT_MAJOR_VERSION 3
#define WINDOW_GL_CONTEXT_MINOR_VERSION 3

#endif
